 
 -------------- celery@worker123 v5.5.3 (immunity)
--- ***** ----- 
-- ******* ---- macOS-12.1-arm64-arm-64bit 2025-09-13 11:22:26
- *** --- * --- 
- ** ---------- [config]
- ** ---------- .> app:         your_project:0x1020bfbb0
- ** ---------- .> transport:   amqps://qzibflvl:**@possum.lmq.cloudamqp.com:5671/qzibflvl
- ** ---------- .> results:     rpc://
- *** --- * --- .> concurrency: 8 (prefork)
-- ******* ---- .> task events: OFF (enable -E to monitor tasks in this worker)
--- ***** ----- 
 -------------- [queues]
                .> celery           exchange=celery(direct) key=celery
                

[tasks]
  . product_api.tasks.flag_suspicious_ips
  . product_api.tasks.save_daily_sales_task
  . product_api.tasks.send_low_stock_email
  . product_api.tasks.send_order_confirmation_email

[2025-09-13 11:22:29,118: INFO/MainProcess] Connected to amqps://qzibflvl:**@possum.lmq.cloudamqp.com:5671/qzibflvl
[2025-09-13 11:22:31,472: INFO/MainProcess] mingle: searching for neighbors
[2025-09-13 11:22:36,999: INFO/MainProcess] mingle: all alone
[2025-09-13 11:22:41,384: INFO/MainProcess] celery@worker123 ready.
[2025-09-13 11:28:14,193: INFO/MainProcess] sync with celery@OYINKANSOLAs-MacBook-Pro.local
[2025-09-13 11:28:17,342: INFO/MainProcess] missed heartbeat from celery@OYINKANSOLAs-MacBook-Pro.local
[2025-09-13 11:32:12,432: INFO/MainProcess] missed heartbeat from celery@OYINKANSOLAs-MacBook-Pro.local
[2025-09-13 18:00:49,435: WARNING/MainProcess] consumer: Connection to broker lost. Trying to re-establish the connection...
Traceback (most recent call last):
  File "/Users/Pro/Downloads/alx-project-nexus/nvenv/lib/python3.10/site-packages/celery/worker/consumer/consumer.py", line 341, in start
    blueprint.start(self)
  File "/Users/Pro/Downloads/alx-project-nexus/nvenv/lib/python3.10/site-packages/celery/bootsteps.py", line 116, in start
    step.start(parent)
  File "/Users/Pro/Downloads/alx-project-nexus/nvenv/lib/python3.10/site-packages/celery/worker/consumer/consumer.py", line 772, in start
    c.loop(*c.loop_args())
  File "/Users/Pro/Downloads/alx-project-nexus/nvenv/lib/python3.10/site-packages/celery/worker/loops.py", line 97, in asynloop
    next(loop)
  File "/Users/Pro/Downloads/alx-project-nexus/nvenv/lib/python3.10/site-packages/kombu/asynchronous/hub.py", line 373, in create_loop
    cb(*cbargs)
  File "/Users/Pro/Downloads/alx-project-nexus/nvenv/lib/python3.10/site-packages/kombu/transport/base.py", line 248, in on_readable
    reader(loop)
  File "/Users/Pro/Downloads/alx-project-nexus/nvenv/lib/python3.10/site-packages/kombu/transport/base.py", line 230, in _read
    drain_events(timeout=0)
  File "/Users/Pro/Downloads/alx-project-nexus/nvenv/lib/python3.10/site-packages/amqp/connection.py", line 526, in drain_events
    while not self.blocking_read(timeout):
  File "/Users/Pro/Downloads/alx-project-nexus/nvenv/lib/python3.10/site-packages/amqp/connection.py", line 531, in blocking_read
    frame = self.transport.read_frame()
  File "/Users/Pro/Downloads/alx-project-nexus/nvenv/lib/python3.10/site-packages/amqp/transport.py", line 297, in read_frame
    frame_header = read(7, True)
  File "/Users/Pro/Downloads/alx-project-nexus/nvenv/lib/python3.10/site-packages/amqp/transport.py", line 587, in _read
    raise OSError('Server unexpectedly closed connection')
OSError: Server unexpectedly closed connection
[2025-09-13 18:00:49,498: WARNING/MainProcess] /Users/Pro/Downloads/alx-project-nexus/nvenv/lib/python3.10/site-packages/celery/worker/consumer/consumer.py:392: CPendingDeprecationWarning: 
In Celery 5.1 we introduced an optional breaking change which
on connection loss cancels all currently executed tasks with late acknowledgement enabled.
These tasks cannot be acknowledged as the connection is gone, and the tasks are automatically redelivered
back to the queue. You can enable this behavior using the worker_cancel_long_running_tasks_on_connection_loss
setting. In Celery 5.1 it is set to False by default. The setting will be set to True by default in Celery 6.0.

  warnings.warn(CANCEL_TASKS_BY_DEFAULT, CPendingDeprecationWarning)

[2025-09-13 18:00:53,831: ERROR/MainProcess] consumer: Cannot connect to amqps://qzibflvl:**@possum.lmq.cloudamqp.com:5671/qzibflvl: _ssl.c:990: The handshake operation timed out.
Trying again in 2.00 seconds... (1/100)

[2025-09-13 18:00:59,799: INFO/MainProcess] Connected to amqps://qzibflvl:**@possum.lmq.cloudamqp.com:5671/qzibflvl
[2025-09-13 18:01:09,950: INFO/MainProcess] mingle: searching for neighbors
[2025-09-13 18:01:19,406: WARNING/MainProcess] consumer: Connection to broker lost. Trying to re-establish the connection...
Traceback (most recent call last):
  File "/Users/Pro/Downloads/alx-project-nexus/nvenv/lib/python3.10/site-packages/celery/worker/consumer/consumer.py", line 341, in start
    blueprint.start(self)
  File "/Users/Pro/Downloads/alx-project-nexus/nvenv/lib/python3.10/site-packages/celery/bootsteps.py", line 116, in start
    step.start(parent)
  File "/Users/Pro/Downloads/alx-project-nexus/nvenv/lib/python3.10/site-packages/celery/worker/consumer/mingle.py", line 37, in start
    self.sync(c)
  File "/Users/Pro/Downloads/alx-project-nexus/nvenv/lib/python3.10/site-packages/celery/worker/consumer/mingle.py", line 41, in sync
    replies = self.send_hello(c)
  File "/Users/Pro/Downloads/alx-project-nexus/nvenv/lib/python3.10/site-packages/celery/worker/consumer/mingle.py", line 54, in send_hello
    replies = inspect.hello(c.hostname, our_revoked._data) or {}
  File "/Users/Pro/Downloads/alx-project-nexus/nvenv/lib/python3.10/site-packages/celery/app/control.py", line 389, in hello
    return self._request('hello', from_node=from_node, revoked=revoked)
  File "/Users/Pro/Downloads/alx-project-nexus/nvenv/lib/python3.10/site-packages/celery/app/control.py", line 106, in _request
    return self._prepare(self.app.control.broadcast(
  File "/Users/Pro/Downloads/alx-project-nexus/nvenv/lib/python3.10/site-packages/celery/app/control.py", line 777, in broadcast
    return self.mailbox(conn)._broadcast(
  File "/Users/Pro/Downloads/alx-project-nexus/nvenv/lib/python3.10/site-packages/kombu/pidbox.py", line 346, in _broadcast
    return self._collect(reply_ticket, limit=limit,
  File "/Users/Pro/Downloads/alx-project-nexus/nvenv/lib/python3.10/site-packages/kombu/pidbox.py", line 385, in _collect
    with consumer:
  File "/Users/Pro/Downloads/alx-project-nexus/nvenv/lib/python3.10/site-packages/kombu/messaging.py", line 464, in __enter__
    self.consume()
  File "/Users/Pro/Downloads/alx-project-nexus/nvenv/lib/python3.10/site-packages/kombu/messaging.py", line 514, in consume
    self._basic_consume(T, no_ack=no_ack, nowait=False)
  File "/Users/Pro/Downloads/alx-project-nexus/nvenv/lib/python3.10/site-packages/kombu/messaging.py", line 641, in _basic_consume
    queue.consume(tag, self._receive_callback,
  File "/Users/Pro/Downloads/alx-project-nexus/nvenv/lib/python3.10/site-packages/kombu/entity.py", line 750, in consume
    return self.channel.basic_consume(
  File "/Users/Pro/Downloads/alx-project-nexus/nvenv/lib/python3.10/site-packages/amqp/channel.py", line 1574, in basic_consume
    p = self.send_method(
  File "/Users/Pro/Downloads/alx-project-nexus/nvenv/lib/python3.10/site-packages/amqp/abstract_channel.py", line 79, in send_method
    return self.wait(wait, returns_tuple=returns_tuple)
  File "/Users/Pro/Downloads/alx-project-nexus/nvenv/lib/python3.10/site-packages/amqp/abstract_channel.py", line 99, in wait
    self.connection.drain_events(timeout=timeout)
  File "/Users/Pro/Downloads/alx-project-nexus/nvenv/lib/python3.10/site-packages/amqp/connection.py", line 526, in drain_events
    while not self.blocking_read(timeout):
  File "/Users/Pro/Downloads/alx-project-nexus/nvenv/lib/python3.10/site-packages/amqp/connection.py", line 531, in blocking_read
    frame = self.transport.read_frame()
  File "/Users/Pro/Downloads/alx-project-nexus/nvenv/lib/python3.10/site-packages/amqp/transport.py", line 297, in read_frame
    frame_header = read(7, True)
  File "/Users/Pro/Downloads/alx-project-nexus/nvenv/lib/python3.10/site-packages/amqp/transport.py", line 577, in _read
    s = recv(n - len(rbuf))  # see note above
  File "/Users/Pro/.pyenv/versions/3.10.13/lib/python3.10/ssl.py", line 1165, in read
    return self._sslobj.read(len)
TimeoutError: The read operation timed out
[2025-09-13 18:01:23,416: WARNING/MainProcess] /Users/Pro/Downloads/alx-project-nexus/nvenv/lib/python3.10/site-packages/celery/worker/consumer/consumer.py:392: CPendingDeprecationWarning: 
In Celery 5.1 we introduced an optional breaking change which
on connection loss cancels all currently executed tasks with late acknowledgement enabled.
These tasks cannot be acknowledged as the connection is gone, and the tasks are automatically redelivered
back to the queue. You can enable this behavior using the worker_cancel_long_running_tasks_on_connection_loss
setting. In Celery 5.1 it is set to False by default. The setting will be set to True by default in Celery 6.0.

  warnings.warn(CANCEL_TASKS_BY_DEFAULT, CPendingDeprecationWarning)

[2025-09-13 18:01:26,524: INFO/MainProcess] Connected to amqps://qzibflvl:**@possum.lmq.cloudamqp.com:5671/qzibflvl
[2025-09-13 18:01:32,861: INFO/MainProcess] mingle: searching for neighbors
[2025-09-13 18:01:37,820: INFO/MainProcess] mingle: all alone
[2025-09-13 18:08:34,323: WARNING/MainProcess] consumer: Connection to broker lost. Trying to re-establish the connection...
Traceback (most recent call last):
  File "/Users/Pro/Downloads/alx-project-nexus/nvenv/lib/python3.10/site-packages/celery/worker/consumer/consumer.py", line 341, in start
    blueprint.start(self)
  File "/Users/Pro/Downloads/alx-project-nexus/nvenv/lib/python3.10/site-packages/celery/bootsteps.py", line 116, in start
    step.start(parent)
  File "/Users/Pro/Downloads/alx-project-nexus/nvenv/lib/python3.10/site-packages/celery/worker/consumer/consumer.py", line 772, in start
    c.loop(*c.loop_args())
  File "/Users/Pro/Downloads/alx-project-nexus/nvenv/lib/python3.10/site-packages/celery/worker/loops.py", line 97, in asynloop
    next(loop)
  File "/Users/Pro/Downloads/alx-project-nexus/nvenv/lib/python3.10/site-packages/kombu/asynchronous/hub.py", line 373, in create_loop
    cb(*cbargs)
  File "/Users/Pro/Downloads/alx-project-nexus/nvenv/lib/python3.10/site-packages/kombu/transport/base.py", line 248, in on_readable
    reader(loop)
  File "/Users/Pro/Downloads/alx-project-nexus/nvenv/lib/python3.10/site-packages/kombu/transport/base.py", line 230, in _read
    drain_events(timeout=0)
  File "/Users/Pro/Downloads/alx-project-nexus/nvenv/lib/python3.10/site-packages/amqp/connection.py", line 526, in drain_events
    while not self.blocking_read(timeout):
  File "/Users/Pro/Downloads/alx-project-nexus/nvenv/lib/python3.10/site-packages/amqp/connection.py", line 531, in blocking_read
    frame = self.transport.read_frame()
  File "/Users/Pro/Downloads/alx-project-nexus/nvenv/lib/python3.10/site-packages/amqp/transport.py", line 297, in read_frame
    frame_header = read(7, True)
  File "/Users/Pro/Downloads/alx-project-nexus/nvenv/lib/python3.10/site-packages/amqp/transport.py", line 587, in _read
    raise OSError('Server unexpectedly closed connection')
OSError: Server unexpectedly closed connection
[2025-09-13 18:08:34,332: WARNING/MainProcess] /Users/Pro/Downloads/alx-project-nexus/nvenv/lib/python3.10/site-packages/celery/worker/consumer/consumer.py:392: CPendingDeprecationWarning: 
In Celery 5.1 we introduced an optional breaking change which
on connection loss cancels all currently executed tasks with late acknowledgement enabled.
These tasks cannot be acknowledged as the connection is gone, and the tasks are automatically redelivered
back to the queue. You can enable this behavior using the worker_cancel_long_running_tasks_on_connection_loss
setting. In Celery 5.1 it is set to False by default. The setting will be set to True by default in Celery 6.0.

  warnings.warn(CANCEL_TASKS_BY_DEFAULT, CPendingDeprecationWarning)

[2025-09-13 18:08:36,615: INFO/MainProcess] Connected to amqps://qzibflvl:**@possum.lmq.cloudamqp.com:5671/qzibflvl
[2025-09-13 18:08:40,820: INFO/MainProcess] mingle: searching for neighbors
[2025-09-13 18:08:44,393: INFO/MainProcess] mingle: all alone

worker: Warm shutdown (MainProcess)
